version: '3.8'
services:
  traefik:
    container_name: toeggelomat_traefik
    image: traefik:v2.0
    ports:
      - 81:80
      - 8181:8080
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock

  #  frontend:
  #    container_name: toeggelomat_frontend
  #    image: spoud/toeggelomat-frontend:kafka
  #    build: frontend/
  #    ports:
  #      - 82:80
  #    labels:
  #      - traefik.http.routers.toeggelomat_frontend.rule=PathPrefix(`/`)
  #      - traefik.http.services.toeggelomat_frontend-service.loadbalancer.server.port=80
  #      - traefik.enable=true
  #
  #  backend:
  #    container_name: toeggelomat_backend
  #    image: spoud/toeggelomat-backend:kafka
  #    build:
  #      context: backend
  #      dockerfile: src/main/docker/Dockerfile.jvm
  ##      dockerfile: src/main/docker/Dockerfile.native
  #    ports:
  #      - 8080
  #    labels:
  #      - traefik.http.routers.toeggelomat_backend.rule=PathPrefix(`/api`)
  #      - traefik.http.services.toeggelomat_backend-service.loadbalancer.server.port=8080
  #      - traefik.enable=true

  kafka:
    container_name: kafka-1
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.10.0
    hostname: ksqldb-server
    container_name: toeggelomat_ksqldb-server
    volumes:
      - ./kafka/ksql:/etc/ksql/queries/
    depends_on: 
      - kafka
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_QUERIES_FILE: /etc/ksql/queries/player.sql

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.10.0
    container_name: toeggelomat_ksqldb-cli
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true
      
