## traefik.yml

debug: true

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    exposedByDefault: false

# API and dashboard configuration
api:
  insecure: true